[mqtt]
uri = "wss://meri.digitraffic.fi:443/mqtt"
topics = ["vessels-v2/+/location", "vessels-v2/+/metadata"]
# Client ID for MQTT listener
client_id = "ais-logger-client"

[database]
# URL to the database
url = "postgres://ais-recorder:sika-limppu-naulakkoon-kastehelmi-farsiksi@localhost/ais-recorder"
